### ISSUE TITLE
Option to disable all emojis?

### ISSUE THREAD

**Issue by Nokocchii** [FrancisLaTruelle/DiscordDisableEmojis#1]
Hiya!

this a feature request: would it be possible to have an option to disable every emoji, with maybe then an option to whitelist certain emojis? or something like that? thanks :)

**Comment by FrancisLaTruelle** [comment]
Hello, this is a great idea! I will think about integrating it in a future version. Thank you for your suggestion :)

**Comment by FrancisLaTruelle** [comment]
A new version has just been published (v1.1.0), I hope it will meet your expectations. All the new features are explained on the README, do not hesitate to send me the bugs.

**Comment by Nokocchii** [comment]
thank you!! ❤
